# Generated by Django 3.2.4 on 2021-06-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='point_of_no_return.Artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='point_of_no_return.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='curator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='point_of_no_return.curator'),
            preserve_default=False,
        ),
    ]
