# Generated by Django 3.2.4 on 2021-06-29 20:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('point_of_no_return', '0003_artist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
