# Generated by Django 3.2.4 on 2021-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0009_auto_20210701_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
