# Generated by Django 3.2.4 on 2021-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0011_remove_music_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='artists', to='point_of_no_return.Artist'),
        ),
    ]
