# Generated by Django 3.2.4 on 2021-07-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0012_alter_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_no_return.curator'),
        ),
    ]
