# Generated by Django 3.2.4 on 2021-06-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0005_auto_20210630_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_no_return.comment'),
        ),
    ]
