# Generated by Django 3.2.4 on 2021-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0007_alter_music_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='music',
            name='released_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
