# Generated by Django 3.2.4 on 2021-07-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_no_return', '0010_music_spotify_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='release_year',
        ),
    ]
